---
title: "Loan Default Risk Sample"
output: html_document
date: "2026-06-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load Library
```{r load-library}
# Load required libraries
library(readr)
library(ggplot2)
library(dplyr)
library(knitr)
library(tibble)
library(tidyr)
library(gridExtra)
library(patchwork)
library(caret)
library(tidyverse)
library(rsample)
```

# Data Prep

## Load Data
```{r load-data}

cols_of_interest <- c(
  "loan_status",
  "loan_amnt",
  "term",
  "int_rate",
  "installment",
  "grade",
  "sub_grade",
  "emp_length",
  "home_ownership",
  "annual_inc",
  "verification_status",
  "purpose",
  "dti",
  "delinq_2yrs",
  "fico_range_low",
  "fico_range_high",
  "inq_last_6mths",
  "open_acc",
  "pub_rec",
  "revol_bal",
  "revol_util",
  "total_acc",
  "addr_state",
  "pub_rec_bankruptcies"
)

# load data
df <- read_csv("/home/asorn/Nextcloud/Data Science/Projects/loan-default-risk/data/raw/accepted_2007_to_2018Q4.csv.gz",
                   col_select = all_of(cols_of_interest))

# standardize names
names(df) <- make.names(names(df))
```


# Data Cleaning 

```{r re-code-target}
df <- df %>%
  filter(loan_status %in% c("Fully Paid", "Charged Off")) %>%
  mutate(default = ifelse(loan_status == "Charged Off", 1, 0)) %>%
  select(-loan_status)
```

```{r fix-datatypes}
df <- df %>%
  mutate(
    term = as.factor(str_trim(term)),
    int_rate = as.numeric(str_remove(int_rate, "%")),
    revol_util = as.numeric(str_remove(revol_util, "%")),
    emp_length = as.factor(emp_length),
    grade = as.factor(grade),
    sub_grade = as.factor(sub_grade),
    home_ownership = as.factor(home_ownership),
    verification_status = as.factor(verification_status),
    purpose = as.factor(purpose),
    addr_state = as.factor(addr_state)
  )
```
  
```{r missing-val}
# check for missing values
missing_tbl <- tibble(
  Variable = names(df),
  MissingN = sapply(df, function(x) sum(is.na(x))),
  MissingPct = sapply(df, function(x) mean(is.na(x)) * 100)
) %>%
  arrange(desc(MissingPct))

kable(head(missing_tbl, 20), digits = 2)
```


```{r drop-missing-rows}
df <- df %>% drop_na()
```


```{r check-class-imbalance}
table(df$default)
prop.table(table(df$default))
```



```{r data-sample}
set.seed(42)
df_sample <- df %>%
  group_by(default) %>%
  slice_sample(n = 50000) %>%
  ungroup()

table(df_sample$default)
```



```{r save-sampledata}
write.csv(df_sample, "sample_2007_to_2018Q4.csv", row.names = FALSE)
```

